/**
 * District-specific Story Arcs — Each district gets a unique 3-step storyline
 * that activates when the player owns that district.
 * Uses the existing StoryArcTemplate format for full compatibility.
 */

import type { StoryArcTemplate } from './storyArcs';

export const DISTRICT_STORY_ARCS: StoryArcTemplate[] = [
  // ===== PORT NERO: DE VERDWENEN LADING =====
  {
    id: 'port_lading',
    name: 'De Verdwenen Lading',
    description: 'Een mysterieuze container verschijnt in de haven. Wat zit erin — drugs, wapens, of iets veel ergers?',
    icon: '📦',
    triggerConditions: { minDay: 2, requiredDistrict: 'port', maxActiveArcs: 2 },
    completionReward: { money: 15000, rep: 120, dirtyMoney: 10000, heat: 5 },
    steps: [
      {
        id: 'pl_1',
        text: 'Een van je havenarbeiders meldt een ongemarkeerde container die vannacht is afgeleverd. Geen papieren, geen afzender. De container staat te trillen — er zit iets levends in. Of iemand.',
        phonePreview: '"Baas, er staat een verdachte container op Dok 7. Geen papieren. Kom kijken?" — Havenarbeider',
        phoneFrom: 'anonymous',
        choices: [
          { id: 'pl_1a', label: 'OPEN DE CONTAINER', stat: 'muscle', difficulty: 25,
            successText: 'Je breekt het slot. Binnenin: kratten vol ongemarkeerde medicijnen uit Azië. Miljoenen waard op de zwarte markt.',
            failText: 'Het slot is versterkt. Je maakt lawaai en de havenwacht komt kijken.',
            effects: { money: 0, heat: 5, rep: 15, dirtyMoney: 5000, crewDamage: 0, karma: -5 } },
          { id: 'pl_1b', label: 'ONDERZOEK DE AFZENDER', stat: 'brains', difficulty: 30,
            successText: 'Via oude contacten ontdek je dat de container toebehoort aan een Aziatisch syndicaat. Ze zoeken een lokale partner.',
            failText: 'Je zoektocht leidt nergens heen. De container blijft een mysterie.',
            effects: { money: 0, heat: 0, rep: 10, dirtyMoney: 0, crewDamage: 0 } },
          { id: 'pl_1c', label: 'MELD HET BIJ DE DOUANE', stat: 'charm', difficulty: 20,
            successText: 'De douane is je "dankbaar". Je politierelatie verbetert. Misschien heb je een toekomstige bondgenoot.',
            failText: 'De douane neemt de container in beslag zonder dank. Bureaucraten.',
            effects: { money: 0, heat: -5, rep: 5, dirtyMoney: 0, crewDamage: 0, karma: 10 } },
        ],
      },
      {
        id: 'pl_2',
        text: 'De eigenaar van de container maakt zich bekend: een vrouw genaamd Mei Ling, koerier voor het Dragon Gate syndicaat. "Die lading is van mij. Ik stel voor dat we samenwerken — of ik haal mijn eigen mensen."',
        phonePreview: '"Ik ben Mei Ling. Die container is van mij. We moeten praten." — Onbekend nummer',
        phoneFrom: 'anonymous',
        choices: [
          { id: 'pl_2a', label: 'WERK SAMEN', stat: 'charm', difficulty: 35,
            successText: 'Mei Ling is professioneel. Jullie verdelen de inhoud — zij regelt de export, jij houdt de lokale markt.',
            failText: 'Mei Ling vertrouwt je niet. "Je bent te gretig." Ze trekt zich terug.',
            effects: { money: 5000, heat: 3, rep: 20, dirtyMoney: 8000, crewDamage: 0 } },
          { id: 'pl_2b', label: 'NEEM ALLES', stat: 'muscle', difficulty: 45,
            successText: 'Je crew overmeestert haar beveiliging. "Dit is mijn haven." Mei Ling vlucht, maar je hebt de volledige lading.',
            failText: 'Haar beveiliging is professioneel. Een kort vuurgevecht — je crew raakt gewond.',
            effects: { money: 0, heat: 12, rep: 30, dirtyMoney: 15000, crewDamage: 15, karma: -10 } },
        ],
      },
      {
        id: 'pl_3',
        text: 'De situatie escaleert. Het Dragon Gate syndicaat stuurt meer mensen. Ze willen de haven als doorvoerhaven voor heel Europa. Jij bent de poortwachter — dat maakt je machtig, maar ook een doelwit.',
        phonePreview: '"Dragon Gate wil permanente doorvoer via Port Nero. Dit is groter dan wij dachten."',
        phoneFrom: 'anonymous',
        choices: [
          { id: 'pl_3a', label: 'WORD HUN PARTNER', stat: 'charm', difficulty: 40,
            successText: 'Je sluit een permanent contract. 15% van alles wat door de haven gaat, is voor jou. Een stroom van geld.',
            failText: 'Ze accepteren het partnerschap maar op hun voorwaarden. Je krijgt slechts 5%.',
            effects: { money: 10000, heat: 5, rep: 40, dirtyMoney: 20000, crewDamage: 0, karma: -5 } },
          { id: 'pl_3b', label: 'BLOKKEER DE HAVEN', stat: 'muscle', difficulty: 50,
            successText: 'Je sluit de haven af voor buitenlandse organisaties. Dragon Gate trekt zich terug. De haven is onbetwist van jou.',
            failText: 'Dragon Gate vecht terug. Een nacht vol geweld, maar je houdt stand.',
            effects: { money: 0, heat: 15, rep: 50, dirtyMoney: 0, crewDamage: 20, karma: 5 } },
          { id: 'pl_3c', label: 'SPEEL DUBBEL SPEL', stat: 'brains', difficulty: 55,
            successText: 'Je verkoopt info over Dragon Gate aan de politie terwijl je hun geld aanneemt. Riskant, maar lucratief.',
            failText: 'Beide partijen komen erachter. Je hebt twee vijanden gemaakt.',
            effects: { money: 8000, heat: -10, rep: 20, dirtyMoney: 10000, crewDamage: 0, karma: -15 } },
        ],
      },
    ],
  },

  // ===== CROWN HEIGHTS: DE GOUDEN GIJZELING =====
  {
    id: 'crown_gijzeling',
    name: 'De Gouden Gijzeling',
    description: 'Een bankiersdochter is ontvoerd in Crown Heights. Jij hebt informatie — en een keuze.',
    icon: '👸',
    triggerConditions: { minDay: 2, requiredDistrict: 'crown', maxActiveArcs: 2 },
    completionReward: { money: 30000, rep: 150, dirtyMoney: 0, heat: -5 },
    steps: [
      {
        id: 'cg_1',
        text: 'Het nieuws gonst door Crown Heights: Isabella van den Berg, dochter van bankier Van den Berg, is ontvoerd. Het losgeld: €2 miljoen. Jouw informanten weten waar ze haar vasthouden.',
        phonePreview: '"De Van den Berg-ontvoering... Ik weet waar ze haar vasthouden." — Straatinformant',
        phoneFrom: 'anonymous',
        choices: [
          { id: 'cg_1a', label: 'RED HAAR', stat: 'muscle', difficulty: 35,
            successText: 'Je crew stormt het pakhuis binnen. Isabella is geschokt maar ongedeerd. "Wie ben jij?" Je hebt een machtige familie in je schuld.',
            failText: 'De ontvoerders waren voorbereid. Je vlucht met lege handen.',
            effects: { money: 0, heat: 10, rep: 30, dirtyMoney: 0, crewDamage: 10, karma: 15 } },
          { id: 'cg_1b', label: 'EIS EEN DEEL VAN HET LOSGELD', stat: 'charm', difficulty: 30,
            successText: 'Je belt de ontvoerders. "30% voor mij, of ik bel de politie." Ze gaan akkoord.',
            failText: 'De ontvoerders lachen. "Bel de politie maar." Ze verplaatsen Isabella.',
            effects: { money: 0, heat: 5, rep: -10, dirtyMoney: 0, crewDamage: 0, karma: -15 } },
          { id: 'cg_1c', label: 'VERKOOP DE INFO AAN POLITIE', stat: 'brains', difficulty: 25,
            successText: 'De politie redt Isabella. Inspecteur Yilmaz beloont je discreet.',
            failText: 'De politie gelooft je niet. De informatie verdwijnt in een dossier.',
            effects: { money: 5000, heat: -8, rep: 10, dirtyMoney: 0, crewDamage: 0, karma: 10 } },
        ],
      },
      {
        id: 'cg_2',
        text: 'De nasleep onthult iets groters. De ontvoerders waren ingehuurd door bankier Vermeer — een concurrent van Van den Berg. Het is een machtsstrijd tussen bankiers, en jij staat ertussenin.',
        phonePreview: '"De ontvoering was een inside job. Bankier Vermeer zit erachter." — Informant',
        phoneFrom: 'anonymous',
        choices: [
          { id: 'cg_2a', label: 'HELP VAN DEN BERG', stat: 'charm', difficulty: 35,
            successText: 'Je levert bewijs van Vermeers betrokkenheid. Van den Berg is je eeuwig dankbaar.',
            failText: 'Het bewijs is niet sterk genoeg. Van den Berg bedankt je maar kan niets bewijzen.',
            effects: { money: 10000, heat: 0, rep: 25, dirtyMoney: 0, crewDamage: 0, karma: 10 } },
          { id: 'cg_2b', label: 'CHANTEER VERMEER', stat: 'brains', difficulty: 40,
            successText: '"Ik weet wat je hebt gedaan, Vermeer." De bankier verbleekt. "Hoeveel?"',
            failText: 'Vermeer is koelbloedig. "Mijn advocaten vernietigen je."',
            effects: { money: 0, heat: 5, rep: 15, dirtyMoney: 15000, crewDamage: 0, karma: -10 } },
          { id: 'cg_2c', label: 'SPEEL BEIDE KANTEN', stat: 'brains', difficulty: 50,
            successText: 'Je verkoopt info aan beide bankiers. Terwijl zij vechten, profiteer jij.',
            failText: 'Beide bankiers komen erachter en keren zich tegen je.',
            effects: { money: 8000, heat: 8, rep: -5, dirtyMoney: 10000, crewDamage: 0, karma: -10 } },
        ],
      },
      {
        id: 'cg_3',
        text: 'Isabella van den Berg belt je. "Ik weet wie je bent. Wat je doet. En ik wil meedoen." Ze biedt toegang tot het financiële netwerk van haar vader — witwassen op een ongekende schaal.',
        phonePreview: '"Ik ben het, Isabella. Ik heb een voorstel dat je niet kunt weigeren." — Isabella',
        phoneFrom: 'anonymous',
        choices: [
          { id: 'cg_3a', label: 'ACCEPTEER HAAR AANBOD', stat: 'charm', difficulty: 35,
            successText: 'Isabella wordt je financiële genie. Via haar vaders netwerk was je meer geld wit dan ooit.',
            failText: 'Isabella is onervaren. Haar eerste poging gaat bijna mis.',
            effects: { money: 20000, heat: 0, rep: 40, dirtyMoney: 0, crewDamage: 0, karma: -5 } },
          { id: 'cg_3b', label: 'WIJS HAAR AF', stat: 'brains', difficulty: 20,
            successText: '"Te gevaarlijk voor ons allebei." Isabella respecteert je eerlijkheid.',
            failText: 'Isabella is teleurgesteld. Ze verdwijnt in de schaduwen van Crown Heights.',
            effects: { money: 5000, heat: -5, rep: 20, dirtyMoney: 0, crewDamage: 0, karma: 10 } },
        ],
      },
    ],
  },

  // ===== IRON BOROUGH: DE FABRIEKSBRAND =====
  {
    id: 'iron_fabriek',
    name: 'De Fabrieksbrand',
    description: 'Een explosie in Iron Borough onthult een ondergronds tunnelnetwerk. Wie heeft het gebouwd?',
    icon: '🔥',
    triggerConditions: { minDay: 2, requiredDistrict: 'iron', maxActiveArcs: 2 },
    completionReward: { money: 18000, rep: 130, dirtyMoney: 8000, heat: 0 },
    steps: [
      {
        id: 'if_1',
        text: 'Een explosie verscheurt de oude Kramer-fabriek. Terwijl het stof neerdaalt, zie je het: een gapend gat in de vloer. Een tunnel — oud, maar goed onderhouden. Iemand heeft dit gebouwd, in het geheim.',
        phonePreview: '"Explosie in de Kramer-fabriek! Er zit een tunnelsysteem onder. Je moet dit zien." — Crew',
        phoneFrom: 'anonymous',
        choices: [
          { id: 'if_1a', label: 'VERKEN DE TUNNELS', stat: 'brains', difficulty: 30,
            successText: 'De tunnels strekken zich kilometers uit. Opslagruimtes, rails, zelfs een ondergrondse haven. Een smokkelnetwerk uit de jaren 70.',
            failText: 'Je raakt verdwaald in het donker. Na uren vind je de uitgang — met een blauw oog.',
            effects: { money: 0, heat: 3, rep: 15, dirtyMoney: 0, crewDamage: 5 } },
          { id: 'if_1b', label: 'BEVEILIG DE INGANG', stat: 'muscle', difficulty: 25,
            successText: 'Je plaatst je eigen mannen bij de ingang. Niemand komt erin zonder jouw toestemming.',
            failText: 'Andere partijen hebben de tunnels ook ontdekt. Je bent niet alleen.',
            effects: { money: 0, heat: 5, rep: 10, dirtyMoney: 0, crewDamage: 0 } },
        ],
      },
      {
        id: 'if_2',
        text: 'In de tunnels vind je overblijfselen: oude wapenkratten, vervalste paspoorten, en een dagboek. De tunnels werden gebouwd door "De Smid" — een legendarische figuur. En zijn kleinzoon wil ze terug.',
        phonePreview: '"De tunnels zijn van De Smid. En zijn kleinzoon Erik wil ze terug claimen." — Oude Marco',
        phoneFrom: 'anonymous',
        choices: [
          { id: 'if_2a', label: 'ONTMOET DE KLEINZOON', stat: 'charm', difficulty: 35,
            successText: 'Erik Kramer is een ingenieur. "Mijn opa bouwde dit voor de vrijheid." Hij geeft je de bouwtekeningen.',
            failText: 'Erik vertrouwt je niet. "Jij bent net als de rest." Hij verdwijnt.',
            effects: { money: 0, heat: 0, rep: 20, dirtyMoney: 0, crewDamage: 0, karma: 5 } },
          { id: 'if_2b', label: 'CLAIM MET GEWELD', stat: 'muscle', difficulty: 40,
            successText: 'Je plaatst explosieven bij de andere ingangen. De tunnels zijn nu exclusief van jou.',
            failText: 'De explosie veroorzaakt een instorting. Een deel is onbruikbaar.',
            effects: { money: 0, heat: 10, rep: 15, dirtyMoney: 5000, crewDamage: 10, karma: -10 } },
          { id: 'if_2c', label: 'VERKOOP DE LOCATIE', stat: 'brains', difficulty: 30,
            successText: 'Je verkoopt de tunnelkaarten aan de Iron Skulls. Ze betalen goed.',
            failText: 'De Iron Skulls betalen minder dan beloofd. Maar een deal is een deal.',
            effects: { money: 8000, heat: 5, rep: -5, dirtyMoney: 0, crewDamage: 0, karma: -5 } },
        ],
      },
      {
        id: 'if_3',
        text: 'De tunnels zijn operationeel. Je hebt een keuze: smokkelroute, vluchtnetwerk, of wapenarsenaal. Elke keuze verandert Iron Borough — en jouw positie in de stad.',
        phonePreview: '"De tunnels zijn klaar. Smokkel, vluchtroute, of arsenaal?" — Crew',
        phoneFrom: 'anonymous',
        choices: [
          { id: 'if_3a', label: 'SMOKKELROUTE', stat: 'brains', difficulty: 35,
            successText: 'De tunnels worden de ruggengraat van je smokkeloperatie. Goederen bewegen onzichtbaar door de stad.',
            failText: 'De eerste lading wordt onderschept bij een instorting. Reparaties nodig.',
            effects: { money: 10000, heat: 3, rep: 30, dirtyMoney: 10000, crewDamage: 0 } },
          { id: 'if_3b', label: 'VLUCHTNETWERK', stat: 'brains', difficulty: 30,
            successText: 'Bij elke politie-inval verdwijn je als een geest. Niemand kan je pakken.',
            failText: 'Het netwerk werkt, maar is langzaam. Niet ideaal bij een echte achtervolging.',
            effects: { money: 5000, heat: -15, rep: 20, dirtyMoney: 0, crewDamage: 0, karma: 5 } },
          { id: 'if_3c', label: 'WAPENARSENAAL', stat: 'muscle', difficulty: 40,
            successText: 'Het grootste illegale wapendepot van Noxhaven. Iron Borough is nu onneembaar.',
            failText: 'Een deel ontploft door vocht. Schade, maar de rest is veilig.',
            effects: { money: 0, heat: 8, rep: 40, dirtyMoney: 8000, crewDamage: 5, karma: -5 } },
        ],
      },
    ],
  },

  // ===== LOWRISE: HET KIND VAN DE STRAAT =====
  {
    id: 'low_kind',
    name: 'Het Kind van de Straat',
    description: 'Een weeskind steelt van je in Lowrise. Straf je hem, of neem je hem onder je hoede?',
    icon: '👦',
    triggerConditions: { minDay: 2, requiredDistrict: 'low', maxActiveArcs: 2 },
    completionReward: { money: 8000, rep: 180, dirtyMoney: 0, heat: -10 },
    steps: [
      {
        id: 'lk_1',
        text: 'Een kind van een jaar of twaalf jat je portemonnee in het steegje bij de metro. Je crew grijpt hem — een mager jochie met vuile kleren en uitdagende ogen. "Laat me los! Ik heb niks gedaan!"',
        phonePreview: '"Baas, we hebben die zakkenroller. Een kind. Wat doen we?" — Crew',
        phoneFrom: 'anonymous',
        choices: [
          { id: 'lk_1a', label: 'LAAT HEM GAAN', stat: 'charm', difficulty: 15,
            successText: 'Je geeft hem zijn vrijheid én je portemonnee. "Koop eten, geen drugs." Het kind kijkt je ongelovig aan.',
            failText: 'Het kind spuugt naar je terwijl het wegrent. Geen dankbaarheid hier.',
            effects: { money: -500, heat: 0, rep: 10, dirtyMoney: 0, crewDamage: 0, karma: 15 } },
          { id: 'lk_1b', label: 'LEER HEM EEN LES', stat: 'muscle', difficulty: 20,
            successText: 'Je schudt hem door elkaar. "Je steelt niet van mij." Het kind beeft maar knikt.',
            failText: 'Het kind schreeuwt. Buurtbewoners kijken. Geen goed beeld.',
            effects: { money: 0, heat: 3, rep: -5, dirtyMoney: 0, crewDamage: 0, karma: -15 } },
          { id: 'lk_1c', label: 'NEEM HEM MEE', stat: 'charm', difficulty: 25,
            successText: '"Hoe heet je?" "...Daan." Je neemt hem mee voor een warme maaltijd. Voor het eerst kijkt iemand naar hem om.',
            failText: 'Het kind vertrouwt je niet. "Ik ga niet met vreemden mee." Slim joch.',
            effects: { money: -200, heat: 0, rep: 15, dirtyMoney: 0, crewDamage: 0, karma: 20 } },
        ],
      },
      {
        id: 'lk_2',
        text: 'Daan verschijnt opnieuw — geslagen, één oog dichtgeslagen. "De Ratten. Ze willen dat ik voor ze werk." De Ratten zijn een kindbende in de kelders van Lowrise.',
        phonePreview: '"Dat jochie staat weer bij de deur. In elkaar geslagen. Vraagt naar jou." — Crew',
        phoneFrom: 'anonymous',
        choices: [
          { id: 'lk_2a', label: 'BESCHERM HEM', stat: 'charm', difficulty: 30,
            successText: 'Je geeft Daan een veilige plek. Je crew houdt een oogje in het zeil. Voor het eerst slaapt hij veilig.',
            failText: 'Daan rent weg als hij je crew ziet. Te veel slechte ervaringen.',
            effects: { money: -1000, heat: 0, rep: 20, dirtyMoney: 0, crewDamage: 0, karma: 15 } },
          { id: 'lk_2b', label: 'VERNIETIG DE RATTEN', stat: 'muscle', difficulty: 40,
            successText: 'Je crew ruimt de kelders op. De Ratten-bende is geschiedenis. Tientallen kinderen zijn vrij.',
            failText: 'De Ratten zijn talrijker dan verwacht. Je wint, maar niet zonder schade.',
            effects: { money: 0, heat: 8, rep: 35, dirtyMoney: 0, crewDamage: 15, karma: 10 } },
          { id: 'lk_2c', label: 'NEGEER HET', stat: 'brains', difficulty: 10,
            successText: 'Niet jouw probleem. Je draait je om. Daan verdwijnt in de nacht.',
            failText: 'Je negeert hem. Lowrise herinnert zich.',
            effects: { money: 0, heat: 0, rep: -10, dirtyMoney: 0, crewDamage: 0, karma: -20 } },
        ],
      },
      {
        id: 'lk_3',
        text: 'Maanden later. Daan is gegroeid. Hij kent elke steeg, elk gezicht, elk geheim van Lowrise. "Ik wil voor je werken. Echt werken."',
        phonePreview: '"Daan wil officieel bij de crew. Hij kent elke hoek van Lowrise." — Crew',
        phoneFrom: 'anonymous',
        choices: [
          { id: 'lk_3a', label: 'NEEM HEM AAN ALS INFORMANT', stat: 'charm', difficulty: 25,
            successText: 'Daan wordt je beste informant. Zijn kennis van de straat is ongeëvenaard. Lowrise heeft een beschermer.',
            failText: 'Daan is enthousiast maar onervaren. Hij maakt fouten — maar leert snel.',
            effects: { money: 3000, heat: -5, rep: 40, dirtyMoney: 0, crewDamage: 0, karma: 5 } },
          { id: 'lk_3b', label: 'STUUR HEM NAAR SCHOOL', stat: 'brains', difficulty: 20,
            successText: '"School?" Daan kijkt je ongelovig aan. Maar hij gaat. Jaren later stuurt hij een brief: "Bedankt."',
            failText: 'Daan gaat één dag en loopt weg. Maar hij respecteert je poging.',
            effects: { money: -3000, heat: -10, rep: 50, dirtyMoney: 0, crewDamage: 0, karma: 25 } },
          { id: 'lk_3c', label: 'MAAK HEM DEEL VAN DE CREW', stat: 'muscle', difficulty: 30,
            successText: 'Daan begint als loopjongen en werkt zich op. Snel, slim en meedogenloos. Een echte straathond.',
            failText: 'Daan is nog te jong voor het zware werk. Maar zijn loyaliteit is onbetwist.',
            effects: { money: 0, heat: 3, rep: 30, dirtyMoney: 0, crewDamage: 0, karma: -10 } },
        ],
      },
    ],
  },

  // ===== NEON STRIP: DE VALSE JACKPOT =====
  {
    id: 'neon_jackpot',
    name: 'De Valse Jackpot',
    description: 'Het casino in Neon Strip wordt gebruikt voor geldwitwassen door een onbekende organisatie.',
    icon: '🎰',
    triggerConditions: { minDay: 2, requiredDistrict: 'neon', maxActiveArcs: 2 },
    completionReward: { money: 25000, rep: 160, dirtyMoney: 15000, heat: 0 },
    steps: [
      {
        id: 'nj_1',
        text: 'Je accountant ontdekt iets vreemds: het Golden Palace casino wast elke nacht miljoenen via valse jackpots. De eigenaar, "Lucky Lau", is slechts een stroman. Iemand groters trekt aan de touwtjes.',
        phonePreview: '"Het Golden Palace wast miljoenen per nacht. Valse jackpots, fake winnaars." — Accountant',
        phoneFrom: 'anonymous',
        choices: [
          { id: 'nj_1a', label: 'INFILTREER HET CASINO', stat: 'charm', difficulty: 35,
            successText: 'Je wordt VIP-klant. Na weken ontdek je het systeem: elke donderdag, 23:00, worden de machines gemanipuleerd.',
            failText: 'De beveiliging herkent je. Je wordt "beleefd" de deur gewezen.',
            effects: { money: -2000, heat: 3, rep: 15, dirtyMoney: 0, crewDamage: 0 } },
          { id: 'nj_1b', label: 'HACK HUN SYSTEEM', stat: 'brains', difficulty: 40,
            successText: 'Je hacker kraakt het casinosysteem. Transactielogboeken, bankrekeningen, alles.',
            failText: 'Het systeem is beter beveiligd dan verwacht. Je hacker wordt bijna getraceerd.',
            effects: { money: 0, heat: 5, rep: 10, dirtyMoney: 3000, crewDamage: 0 } },
        ],
      },
      {
        id: 'nj_2',
        text: 'De organisatie erachter is de Volkov Bratva — Oost-Europese maffia. Hun leider Sergei Volkov opereert vanuit een penthouse boven het casino. Hij weet dat iemand aan zijn operatie ruikt.',
        phonePreview: '"Sergei Volkov. Bratva. Gevaarlijk. Hij zoekt naar degene die zijn systeem hackte." — Informant',
        phoneFrom: 'anonymous',
        choices: [
          { id: 'nj_2a', label: 'CONFRONTEER VOLKOV', stat: 'muscle', difficulty: 45,
            successText: 'Je trapt zijn penthousedeur open. "Neon Strip is van mij, Sergei." Volkov begrijpt de taal van geweld.',
            failText: 'Volkovs beveiliging is ex-militair. Je overleeft het, maar ternauwernood.',
            effects: { money: 0, heat: 12, rep: 35, dirtyMoney: 0, crewDamage: 20, karma: -5 } },
          { id: 'nj_2b', label: 'BIED EEN DEAL AAN', stat: 'charm', difficulty: 40,
            successText: '"50/50, Sergei. Jij wast, ik bescherm." Sergei grinnikt. "Deal."',
            failText: '"Ik deel niet met straatcriminelen." Sergei weigert koudweg.',
            effects: { money: 5000, heat: 0, rep: 20, dirtyMoney: 10000, crewDamage: 0, karma: -5 } },
          { id: 'nj_2c', label: 'GEEF HEM AAN BIJ DE POLITIE', stat: 'brains', difficulty: 35,
            successText: 'Een anonieme tip leidt tot een spectaculaire inval. Volkov wordt gearresteerd. Het casino staat leeg.',
            failText: 'Volkov heeft te goede advocaten. Binnen 24 uur is hij vrij — en woedend.',
            effects: { money: 0, heat: -10, rep: 25, dirtyMoney: 0, crewDamage: 0, karma: 15 } },
        ],
      },
      {
        id: 'nj_3',
        text: 'Het Golden Palace staat te koop — of te grijpen. Met Volkov uit de weg heb je de kans om het casino om te bouwen tot het kloppende hart van je imperium.',
        phonePreview: '"Het Golden Palace is beschikbaar. Dit is je kans om Neon Strip écht te beheersen." — Rosa',
        phoneFrom: 'anonymous',
        choices: [
          { id: 'nj_3a', label: 'KOOP HET CASINO', stat: 'charm', difficulty: 35,
            successText: 'Het Golden Palace is van jou. De neonlichten veranderen van kleur — jouw kleur.',
            failText: 'De prijs stijgt door biedoorlogen. Je betaalt meer dan gepland.',
            effects: { money: -15000, heat: 0, rep: 50, dirtyMoney: 20000, crewDamage: 0, karma: 5 } },
          { id: 'nj_3b', label: 'NEEM HET MET GEWELD', stat: 'muscle', difficulty: 50,
            successText: 'Wie heeft papieren nodig? Je crew neemt bezit. Het casino draait — voor jou.',
            failText: 'Een bloedige nacht. Je wint, maar de politie is niet blij.',
            effects: { money: 0, heat: 15, rep: 40, dirtyMoney: 15000, crewDamage: 15, karma: -15 } },
          { id: 'nj_3c', label: 'INSTALLEER EEN STROMAN', stat: 'brains', difficulty: 45,
            successText: 'Je zet een vertrouweling neer als "eigenaar". Op papier schoon, in werkelijkheid van jou.',
            failText: 'Je stroman wordt nerveus. Maar het werkt — voorlopig.',
            effects: { money: 5000, heat: -5, rep: 35, dirtyMoney: 15000, crewDamage: 0, karma: -5 } },
        ],
      },
    ],
  },
];
